version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/nicolaferraro/datamesh
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            go get -u github.com/golang/dep/cmd/dep
            dep ensure
      - run:
          name: Build
          command: |
            go build
            go test -v ./...
      - setup_remote_docker
      - run:
          name: Push Docker Image
          command: |
            docker build -t nicolaferraro/datamesh:latest .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push nicolaferraro/datamesh:latest
