// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/datamesh.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	service/datamesh.proto

It has these top-level messages:
	Event
	Empty
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Event)(nil), "service.Event")
	proto.RegisterType((*Empty)(nil), "service.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DataMesh service

type DataMeshClient interface {
	Push(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Empty, error)
}

type dataMeshClient struct {
	cc *grpc.ClientConn
}

func NewDataMeshClient(cc *grpc.ClientConn) DataMeshClient {
	return &dataMeshClient{cc}
}

func (c *dataMeshClient) Push(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/service.DataMesh/Push", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DataMesh service

type DataMeshServer interface {
	Push(context.Context, *Event) (*Empty, error)
}

func RegisterDataMeshServer(s *grpc.Server, srv DataMeshServer) {
	s.RegisterService(&_DataMesh_serviceDesc, srv)
}

func _DataMesh_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataMeshServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.DataMesh/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataMeshServer).Push(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataMesh_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.DataMesh",
	HandlerType: (*DataMeshServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _DataMesh_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/datamesh.proto",
}

func init() { proto.RegisterFile("service/datamesh.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x4f, 0x49, 0x2c, 0x49, 0xcc, 0x4d, 0x2d, 0xce, 0xd0, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x87, 0x8a, 0x2b, 0x99, 0x72, 0xb1, 0xba, 0x96, 0xa5, 0xe6, 0x95, 0x08,
	0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9,
	0x42, 0x12, 0x5c, 0xec, 0x05, 0x89, 0x95, 0x39, 0xf9, 0x89, 0x29, 0x12, 0x4c, 0x0a, 0x8c, 0x1a,
	0x3c, 0x41, 0x30, 0xae, 0x12, 0x3b, 0x17, 0xab, 0x6b, 0x6e, 0x41, 0x49, 0xa5, 0x91, 0x09, 0x17,
	0x87, 0x4b, 0x62, 0x49, 0xa2, 0x6f, 0x6a, 0x71, 0x86, 0x90, 0x06, 0x17, 0x4b, 0x40, 0x69, 0x71,
	0x86, 0x10, 0x9f, 0x1e, 0xd4, 0x74, 0x3d, 0xb0, 0xd1, 0x52, 0x48, 0x7c, 0x90, 0x1e, 0x25, 0x86,
	0x24, 0x36, 0xb0, 0x2b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x8f, 0xdc, 0x24, 0x9f,
	0x00, 0x00, 0x00,
}
